start_angular:
  default:
    languages:
      - nodejs20
    steps:
      - run: npm install && npm run build
        path: ./code
      - run: cp nginx.conf ./dist/angular/browser/nginx.conf
        path: ./code
  defaultBuilder:
    languages:
      - nodejs20
    steps:
      - run: npm install && npm run build
        path: ./code
      - run: cp nginx.conf ./dist/angular/browser/nginx.conf
        path: ./code