start_dumi:
  defaultBuilder:
    languages:
      - nodejs20
    steps:
      - run: npm install && npm run build
        path: ./code
      - run: cp nginx.conf ./dist/nginx.conf
        path: ./code